services:
  app:
    build: .
    pull_policy: build
    container_name: antroforms-web-strattos
    restart: always
    env_file:
      - .env
    expose:
      - "3000"
    networks:
      strattos-net:
        aliases:
          - antroforms-web-strattos

networks:
  strattos-net:
    external: true
